# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0002_auto_20170927_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='travels',
            field=models.ManyToManyField(related_name='_user_travels_+', to='logreg.User'),
        ),
    ]
