# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0003_user_travels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='travels',
        ),
    ]
