# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='description',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='travel',
            name='destination',
            field=models.CharField(max_length=50),
        ),
    ]
